name: Backup
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check and release
        run: |
            rm -fr *
            sudo apt update
            sudo apt install upx git -y
            sudo snap install go --classic
            git clone -b master https://github.com/HyNetwork/hysteria hysteria-core> /dev/null
            cd hysteria-core/cmd
            CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -buildid=" -o ../../hysteria
            CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags "-s -w -buildid=" -o ../../hysteria-arm
            cd ../../
            #upx --best hysteria
            rm -rf hysteria-core
            mkdir -p .github/workflows
            wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null
            git config --global init.defaultBranch main
            git init
            git add .
            git config user.name "appleians"
            git config user.email "77714325+appleians@users.noreply.github.com"
            git commit -m "macos amd64 binary"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push origin main --force
